name: CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('back/pom.xml') }}

      - name: Build backend
        run: |
          cd back
          mvn clean install jacoco:report

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: back/target/site/jacoco/

  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('front/package-lock.json') }}

      - name: Build frontend
        run: |
          cd front
          npm install
          npm run test -- --code-coverage --watch=false --browsers=ChromeHeadless
          npm run build

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: front/coverage

  docker-backend:
    needs: backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend
        run: |
          cd back
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest

  docker-frontend:
    needs: frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend
        run: |
          cd front
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest
