name: CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build backend
        run: mvn -f back/pom.xml clean compile package -DskipTests
  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: front/package-lock.json
      - name: Build frontend
        run: |
          cd front
          npm ci
          npm run build
  docker-backend:
    needs: backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend
        run: |
          cd back
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest

  docker-frontend:
    needs: frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend
        run: |
          cd front
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest
