name: Build and Analyze SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Build and Analyze Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('back/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build backend & run tests
        run: |
          cd back
          mvn clean verify

      - name: SonarCloud scan backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd back
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=AnhVaccari_bobapp-cicd \
            -Dsonar.organization=anhvaccari \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

  frontend:
    name: Build and Analyze Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd front
          npm ci

      - name: Run frontend tests with coverage
        run: |
          cd front
          npm run test -- --code-coverage --watch=false --browsers=ChromeHeadless --source-map=false

      - name: Debug coverage location
        run: |
          echo "=== Structure du coverage ==="
          ls -la front/coverage/ || echo "Pas de dossier coverage"
          ls -la front/coverage/bobapp/ || echo "Pas de dossier coverage/bobapp"
          echo "=== Vérification sonar-project.properties ==="
          cat front/sonar-project.properties || echo "Pas de fichier sonar-project.properties"

      - name: SonarCloud Scan Frontend
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          args: >
            -Dsonar.projectKey=anhvaccari_bobapp-frontend
            -Dsonar.organization=anhvaccari
            -Dsonar.sources=front/src
            -Dsonar.tests=front/src
            -Dsonar.test.inclusions=front/**/*.spec.ts
            -Dsonar.exclusions=front/**/node_modules/**,front/**/*.spec.ts,front/**/dist/**,front/**/coverage/**
            -Dsonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info
            -Dsonar.projectBaseDir=./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
