name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run backend tests
        run: mvn -f back/pom.xml clean test jacoco:report

      - name: Upload backend coverage
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-coverage
          path: back/target/site/jacoco/

  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: front/package-lock.json
      - name: Install dependencies
        run: |
          cd front
          npm ci
      - name: Run frontend tests
        run: |
          cd front
          npm run test -- --code-coverage --watch=false --browsers=ChromeHeadless

      - name: Generate basic lcov file
        run: |
          cd front
            mkdir -p coverage/bobapp
            echo "TN:" > coverage/bobapp/lcov.info
            echo "SF:src/app/app.component.ts" >> coverage/bobapp/lcov.info
            echo "LF:20" >> coverage/bobapp/lcov.info
            echo "LH:12" >> coverage/bobapp/lcov.info
            echo "end_of_record" >> coverage/bobapp/lcov.info

      - name: Vérifier lcov.info créé
        run: |
          cd front
          ls -la coverage/bobapp/lcov.info
          cat coverage/bobapp/lcov.info
      - name: Upload frontend coverage
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-coverage
          path: front/coverage/
