name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('back/pom.xml') }}

      - name: Run backend tests
        run: |
          cd back
          mvn clean test jacoco:report

      - name: Upload backend coverage
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-coverage
          path: back/target/site/jacoco/

  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('front/package-lock.json') }}

      - name: Run frontend tests
        run: |
          cd front
          npm install
          npm run test -- --code-coverage --watch=false --browsers=ChromeHeadless

      - name: Upload frontend coverage
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-coverage
          path: front/coverage/
